# This task only creates VW with autoscaling configuration as defined in defaults/main.yml
# applicationConfig changes are applied via Update VW process

# Displays the rendered json template for VW creation with provided autoscaling configuration.
- name: " \U00002795 CREATE: VW {{ vw_default_config_item.key}} with below AutoScaling config"
  debug:
    msg: "{{ lookup('template', path) }}"
  vars:
    path: "{{role_path}}/templates/vw_create_autoscaling_template.json.j2"
    vw_type: "{{ vw_default_config_item.value.vwType }}"
    vw_name: "{{ vw_default_config_item.key }}"
    vw_size: "{{ vw_default_config_item.value.template }}"
    vw_autoscaling: "{{ vw_default_config_item.value.autoscaling | to_json }}"

# VWs are created with autoscaling config and then updated with applicationConfig if defined in defaults/main.yaml
- name: "APPLY mode \U00002795 CREATE: Create VW {{ vw_default_config_item.key}} with autoscaling config"
  command: cdp dw create-vw --cli-input-json {{ lookup('template', path ) | to_json | quote }}
  vars:
    path: "{{role_path}}/templates/vw_create_autoscaling_template.json.j2"
    vw_type: "{{ vw_default_config_item.value.vwType }}"
    vw_name: "{{ vw_default_config_item.key }}"
    vw_size: "{{ vw_default_config_item.value.template }}"
    vw_autoscaling: "{{ vw_default_config_item.value.autoscaling | to_json }}"
  register: create_vw_status
  when: mode == "apply"


- name: Display the vwId of the newly created VW "{{ vw_default_config_item.key }}"
  debug: 
    msg: "{{ create_vw_status.stdout }}"
  when: mode == "apply"

# maintain list of VWs to be updated post creation if applicationConfigs are present in yaml source.
# if applicationConfigs are not present then the VW does not require update process.
- name : update the list of created VWs
  set_fact:
    vw_created: "{{ vw_created + [{'id': vwId, 'name': vw_default_config_item.key}] }}"
  when: mode == "apply" and vw_default_config_item.value.config is defined
  vars:
    vwId: "{{ create_vw_status.stdout | from_json | json_query('vwId') }}"